language: python
python:
  - 2.6
  - 2.7
  - 3.3
install:
  - pip install -r requirements.txt -q --use-mirrors
script:
  - coverage run --source=coveralls setup.py test
  - coverage report -m
  - python setup.py develop
after_script:
  - bin/coveralls --verbose --source-debug

