name: Build

on:
  push:
    tags: ['*']

jobs:
  publish:
    name: upload to PyPI
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4.3.0
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - uses: snok/install-poetry@v1.4.1
        with:
          # TODO: renovate
          version: 1.8.2
      - run: poetry build
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
